FROM ubuntu
RUN apt-get update -y
RUN apt-get install -y apache2 libapache2-mod-proxy-uwsgi
RUN a2enmod headers deflate expires rewrite proxy proxy_uwsgi proxy_http proxy_ajp


RUN chown -R www-data:www-data /var/www

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

COPY 000-default.conf /etc/apache2/sites-enabled/

EXPOSE 80


CMD ["apachectl", "-D",  "FOREGROUND"]

