apiVersion: v1
kind: Service
metadata:
          name: simple-app-service
            labels:
                        app: my-server
                          namespace: devops
                          spec:
                                    type: LoadBalancer
                                      selector:
                                                  app: my-server
                                                    ports:
                                                              - port: 80
                                                                    nodePort: 30001
                                                                        targetPort: 80
                                                                            protocol: TCP

